/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     App
 * Method:    calcBill
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_App_calcBill
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     App
 * Method:    calcTax
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_App_calcTax
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
